apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "searxng.configMapName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "searxng.labels" . | nindent 4 }}
data:
  settings.yml: |
{{- if .Values.config }}
    {{- toYaml .Values.config | nindent 4 }}
{{- else }}
    {{- with .Values.searxng.config }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}