{{- if .Values.redis.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "searxng.fullname" . }}-redis-master
  labels:
    {{- include "searxng.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  type: ClusterIP
  ports:
  - name: redis
    port: 6379
    targetPort: redis
    protocol: TCP
  selector:
    {{- include "searxng.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: redis
{{- end }}
