apiVersion: v1
kind: Service
metadata:
  name: {{ include "searxng.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "searxng.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ default .Values.service.port .Values.service.main.ports.http.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "searxng.selectorLabels" . | nindent 4 }}